cloudinary_cloud_name: "dzzenmck8"
cloudinary_api_key: "942661256859633"
cloudinary_api_secret: "GvXlMPq0o5NQPxgxeb7VyVe32Is"
twitter_app_id: "HVPwzdYfD45mdr6keQFD16Ah"
twitter_app_secret: "X7HXQyAvycoBgm5C3IMcd0rrcZOlaX8joi7DYoBBGDSvNcsCxw"